#!/bin/bash

if [ ! -n "$1" ] ; then
    echo "usage: rflow <command> [args]"
    exit -1
fi

command=$1
shift
args=$@

function pull {
    git checkout master
    git pull upstream master
    # TODO: submodule update has to be run from repo root
    git submodule update
}

function push {
    git checkout master
    git push upstream master
    git push
}

function merge {
    if [ ! -n "$args" ] ; then
        echo "specify a branch to merge"
        exit -1
    fi
    pull
    git checkout "$args"
    if [ "$?" -ne "0" ] ; then
        exit -1
    fi
    git rebase master
    if [ "$?" -ne "0" ] ; then
        exit -1
    fi
    git checkout master
    if [ "$?" -ne "0" ] ; then
        exit -1
    fi
    git merge "$args"
    if [ "$?" -ne "0" ] ; then
        exit -1
    fi
    git branch -d "$args"
}

$command
