#!/bin/bash

if [ ! -n "$1" ] ; then
    echo "usage: rflow <command> [args]"
    exit -1
fi

command=$1
shift
args=$@

function pull {
    git checkout master
    git pull upstream master
    git submodule update
}

function push {
    git checkout master
    git push upstream master
    git push
}

function merge {
    if [ ! -n "$args" ] ; then
        echo "specify a branch to merge"
        exit -1
    fi
    pull
    git checkout "$args"
    git rebase master
    git checkout master
    git merge "$args"
    git branch -d "$args"
}

$command
